import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import Providers from "@/Providers/providers";
import { ToastContainer } from "react-toastify";

const prompt = Prompt({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={prompt.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar></Navbar>
            {children}
            <ToastContainer position="top-center" autoClose={1000} />
            <Footer></Footer>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
